
application: dumbrtc
version: 1
runtime: go
api_version: go1

handlers:
- url: /broker
  script: _go_app
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /
  static_dir: static
  secure: always

